apiVersion: v1
kind: Service              # 1
metadata:
  name: gs-spring-boot-docker
spec:
  type: LoadBalancer       # 2
  ports:
  - port: 80               # 3
    protocol: TCP          # 4
    targetPort: 5000       # 5
  selector:                # 6
    app: gs-spring-boot-docker       # 7
